import { existsSync } from 'node:fs'
import { join } from 'node:path'
import { defineConfig } from '@adonisjs/vite'

// Application root (build folder in production, or web-admin source folder in development)
const appRoot = join(import.meta.dirname, '..')

// Resolve manifest file robustly across monorepo root, standalone build, and Docker container environments
const candidateManifests = [
  join(appRoot, 'public/assets/.vite/manifest.json'),
  join(appRoot, 'build/public/assets/.vite/manifest.json'),
  join(process.cwd(), 'apps/web-admin/build/public/assets/.vite/manifest.json'),
  join(process.cwd(), 'build/public/assets/.vite/manifest.json'),
  join(process.cwd(), 'public/assets/.vite/manifest.json'),
]
const resolvedManifestFile =
  candidateManifests.find((file) => existsSync(file)) || candidateManifests[0]

// Resolve build directory robustly
const candidateBuildDirs = [
  join(appRoot, 'public/assets'),
  join(appRoot, 'build/public/assets'),
  join(process.cwd(), 'apps/web-admin/build/public/assets'),
  join(process.cwd(), 'build/public/assets'),
  join(process.cwd(), 'public/assets'),
]
const resolvedBuildDirectory =
  candidateBuildDirs.find((dir) => existsSync(dir)) || candidateBuildDirs[0]

const viteBackendConfig = defineConfig({
  /**
   * The output of vite will be written inside this
   * directory.
   */
  buildDirectory: resolvedBuildDirectory,

  /**
   * The path to the manifest file generated by the
   * "vite build" command.
   */
  manifestFile: resolvedManifestFile,

  /**
   * Feel free to change the value of the "assetsUrl" to
   * point to a CDN in production.
   */
  assetsUrl: '/assets',

  scriptAttributes: {
    defer: true,
  },
})

export default viteBackendConfig
